export const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "₡" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$" },
  { code: "XPF", name: "CFP Franc", symbol: "₣" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "LAK", name: "Lao Kip", symbol: "₭" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: ".ރ" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "лв" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "лв" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "ALL", name: "Albanian Lek", symbol: "L" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "RSD", name: "Serbian Dinar", symbol: "Дин." },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
  { code: "LTL", name: "Lithuanian Litas", symbol: "Lt" },
  { code: "LVL", name: "Latvian Lats", symbol: "Ls" },
  { code: "EEK", name: "Estonian Kroon", symbol: "kr" },
];

export const getCurrencyByCode = (code: string) => {
  return currencies.find((currency) => currency.code === code);
};

export const formatCurrency = (
  amount: number,
  currencyCode: string = "XOF",
) => {
  const currency = getCurrencyByCode(currencyCode);
  if (!currency) return `$${amount.toLocaleString()}`;

  return `${currency.symbol} ${amount.toLocaleString()}`;
};
